Repository software2uis/msv-catalogo, pull requests merged in 2024-11, with the labels that each got.

#9 Feat/swagger documentation
  README.md
  pom.xml
  src/main/java/com/equipo/catalogo/swagger/SwaggerConfig.java
Labels: enhancement

#17 Add: Endpoint for Suggestions
  src/main/java/com/equipo/catalogo/controller/ProductController.java
  src/main/java/com/equipo/catalogo/repository/interfaces/IProductRepository.java
  src/main/java/com/equipo/catalogo/service/impl/ProductServiceImpl.java
Labels: enhancement

#21 Feat/documentation url
  README.md
  src/main/resources/application.properties
Labels: enhancement

#22 Add build file for sonarqube integration
  .github/workflows/build.yml
Labels: enhancement

#23 feat: modify build to be triggered not only on pushes but also on pull request
  .github/workflows/build.yml
  application.properties
Labels: enhancement

#26 Feat/filters
  src/main/java/com/equipo/catalogo/controller/ProductController.java
Labels: enhancement, fix

#27 Fix/suggestions data type
  application.properties
  src/main/java/com/equipo/catalogo/controller/ProductController.java
  src/main/java/com/equipo/catalogo/service/impl/ProductServiceImpl.java
  src/main/java/com/equipo/catalogo/service/interfaces/IProductService.java
Labels: fix

#28 fix: min and max price filters
  src/main/java/com/equipo/catalogo/repository/impl/ProductCustomRepositoryImpl.java
Labels: fix
